SET currentPath=%~dp0
SET batFolder=detail
SET commonFolder=common
SET batPath=%currentPath%%batFolder%
SET commonPath=%currentPath%%batFolder%/%commonFolder%
rem 1.创建git仓库并创建文件夹和文件
CD %batPath%
CALL 01creatGitFolder
CD %batPath%
CALL 02gitInit
CD %batPath%
CALL 03creatFolderAndText
CD %commonPath%
CALL 01checkStatus
CD %commonPath%
CALL 02checkDiffent
CD %commonPath%
CALL 03addContentToText
CD %commonPath%
CALL 04addText
CD %commonPath%
CALL 05commit
CD %commonPath%
CALL 01checkStatus
CD %commonPath%
CALL 02checkDiffent

rem 2.版本回退
CD %commonPath%
CALL 03addContentToText
CD %commonPath%
CALL 04addText
CD %commonPath%
CALL 05commit
CD %commonPath%
CALL 06checkLog
CD %commonPath%
CALL 07reset
CD %commonPath%
CALL 06checkLog
CD %commonPath%
CALL 09resetPreLog
CD %commonPath%
CALL 06checkLog

rem 3.了解工作区和暂存区
CD %commonPath%
CALL 03addContentToText
CD %batPath%
CALL 05createNewText
CD %commonPath%
CALL 01checkStatus
CD %commonPath%
CALL 04addText
CD %commonPath%
CALL 10addNewText
CD %commonPath%
CALL 01checkStatus
CD %commonPath%
CALL 05commit
CD %commonPath%
CALL 01checkStatus

rem 4.管理修改
CD %commonPath%
CALL 03addContentToText
CD %commonPath%
CALL 04addText
CD %commonPath%
CALL 01checkStatus
CD %commonPath%
CALL 03addContentToText
CD %commonPath%
CALL 05commit
CD %commonPath%
CALL 01checkStatus
CD %commonPath%
CALL 11checkTextDiff

rem 4.撤销修改
CD %commonPath%
CALL 03addContentToText
CD %commonPath%
CALL 01checkStatus
rem 撤回版本库
CD %commonPath%
CALL 12backChange
CD %commonPath%
CALL 01checkStatus
rem 撤回暂存区时的修改
CD %commonPath%
CALL 03addContentToText
CD %commonPath%
CALL 04addText
CD %commonPath%
CALL 03addContentToText
CD %commonPath%
CALL 01checkStatus
CD %commonPath%
CALL 12backChange
CD %commonPath%
CALL 01checkStatus
rem 撤回暂存区的修改
CD %commonPath%
CALL 03addContentToText
CD %commonPath%
CALL 04addText
CD %commonPath%
CALL 01checkStatus
CD %commonPath%
CALL 13resetFile
CD %commonPath%
CALL 01checkStatus
CD %commonPath%
CALL 12backChange
CD %commonPath%
CALL 01checkStatus

rem 5.删除文件
CD %commonPath%
CALL 14deleteNewText
CD %commonPath%
CALL 01checkStatus
CD %batPath%
CALL 06rmGitText
CD %commonPath%
CALL 05commit
CD %commonPath%
CALL 01checkStatus

rem 6.添加远程仓库
CD %batPath%
CALL 07remoteAddOrigin
CD %batPath%
CALL 08firstOriginPush
CD %commonPath%
CALL 03addContentToText
CD %batPath%
CALL 09originPush
CD %commonPath%
CALL 04addText
CD %batPath%
CALL 09originPush
CD %commonPath%
CALL 05commit
CD %batPath%
CALL 09originPush
CD %batPath%
CALL 04deleteGitFolder

rem 7.从远程拉取仓库内容
CD %batPath%
CALL 01creatGitFolder
CD %batPath%
CALL 10CloneGit





rem 删除所有的痕迹
CD %batPath%
CALL 04deleteGitFolder